### ISSUE TITLE
Thanks for making this available!

### ISSUE THREAD

**Issue by billscheidel** [magrinj/react-native-swipeable-view#3]
I've been looking for a simple, straight forward swipeable view for awhile before I came across your library.  Almost all of the other libraries I found assume a certain list implementation or were so complicated they were hard to customize for our needs. This one, however, fit the bill perfectly and we were able to integrate it quickly.  Just wanted to say thanks!

**Comment by magrinj** [comment]
Thanks a lot for your message! Hope this library fit perfectly to your needs! :)
