### ISSUE TITLE
Transparent backgroundColor

### ISSUE THREAD

**Issue by JohanHjalmarsson** [magrinj/react-native-swipeable-view#5]
Hi!
Is there any way to not have the backgroundColor set to white?
Or have I missed something? =)

thanks

**Comment by magrinj** [comment]
Hello,

You're right, actually you can't, but if you want you can make a PR :)

**Comment by JohanHjalmarsson** [comment]
Thanks for quick reply.
My solution now was just to define background color on each child element. That works fine.
I will make a PR when I have some time over. =)

**Comment by magrinj** [comment]
Ok thanks :)
